[tool.poetry]
name = "learning-amqp"
version = "0.1.0"
description = ""
authors = ["Emmanuel Pastor <emmanuel.pastor@momox.biz>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pika = "^1.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
